--get income generated by films

--get number of sold tickets by film

--get number of sold tickets by discount type 
SELECT d.DESCRIPTION, COUNT(*) FROM Sold_tickets t
INNER JOIN Discounts d ON d.ID = t.DISCOUNT_ID
GROUP BY t.DISCOUNT_ID;

--get number of sold tickets and max capacity of the room by past screening. (Occupancy rate)  

--get current films (where screening time is in future)

--get all screenings on 21.12
SELECT f.TITLE FROM Films f
INNER JOIN Screenings s ON s.FILM = f.ID
WHERE s.SCREENING_TIME LIKE '2021-12-21%';

--average ticket price (from sold tickets) 

--how many times a specific film was displayed
SELECT f.TITLE, COUNT(FILM) FROM Screenings s
INNER JOIN Films f ON f.ID = s.FILM 
GROUP BY f.ID;

--the cheapest screening 

--the most expensive screening