ALTER SESSION SET nls_date_format = 'dd-MON-yyyy hh24:mi';

--get income generated by films

SELECT
    f.id      film_id,
    f.title   film_title,
    COUNT(f.id) sold_tickets_num,
    TO_CHAR(SUM(st.price), '9,999.99') income
FROM
    sold_tickets   st
    JOIN screenings     s ON st.screening_id = s.id
    JOIN films          f ON s.film = f.id
GROUP BY
    f.title,
    f.id;

--get number of sold tickets by screenings

SELECT
    s.id      screening_id,
    s.screening_time,
    f.title   film_title,
    COUNT(st.id) sold_tickets_num
FROM
    sold_tickets   st
    JOIN screenings     s ON st.screening_id = s.id
    JOIN films          f ON s.film = f.id
GROUP BY
    st.screening_id,
    f.title,
    s.id,
    s.screening_time;

--get number of sold tickets by discount type 

SELECT
    t.discount_id,
    d.description,
    COUNT(discount_id)
FROM
    sold_tickets   t
    INNER JOIN discounts      d ON d.id = t.discount_id
GROUP BY
    t.discount_id,
    d.description;

--get number of sold tickets and max capacity of the room by past screening. (Occupancy rate)
-- get number of sold tickets and max capacity of the room. (Occupancy rate)

SELECT
    s.id         screening_id,
    s.screening_time,
    f.title      film_title,
    COUNT(st.id) sold_tickets_num,
    r.capacity   all_places,
    TO_CHAR((COUNT(st.id) / r.capacity) * 100, '990.0') occupancy_rate
FROM
    sold_tickets   st
    JOIN screenings     s ON st.screening_id = s.id
    JOIN rooms          r ON s.room = r.id
    JOIN films          f ON s.film = f.id
GROUP BY
    st.screening_id,
    f.title,
    s.id,
    s.screening_time,
    r.capacity;

--get current films (where screening time is in future)

SELECT
    s.id      screening_id,
    f.title   film_title,
    s.screening_time,
    st.type_name,
    r.id      room_number
FROM
    screenings        s
    JOIN films             f ON s.film = f.id
    JOIN rooms             r ON s.room = r.id
    JOIN screening_types   st ON r.screening_type = st.id
WHERE
    s.screening_time > SYSDATE
ORDER BY
    s.screening_time;

--get all screenings on 21.12

SELECT
    s.id,
    f.title,
    s.screening_time,
    st.type_name
FROM
    screenings        s
    JOIN films             f ON s.film = f.id
    JOIN rooms             r ON s.room = r.id
    JOIN screening_types   st ON r.screening_type = st.id
WHERE
    s.screening_time BETWEEN '21-DEC-2021' AND '22-DEC-2021'
ORDER BY
    s.screening_time;

--how many times a specific film is displayed

SELECT
    f.title film_title,
    COUNT(s.film) num_film_was_displayed
FROM
    screenings   s
    JOIN films        f ON s.film = f.id
GROUP BY
    s.film,
    f.title;

-- get programme (all screenings) 

SELECT
    s.id,
    f.title,
    s.screening_time,
    st.type_name
FROM
    screenings        s
    JOIN films             f ON s.film = f.id
    JOIN rooms             r ON s.room = r.id
    JOIN screening_types   st ON r.screening_type = st.id
ORDER BY
    s.screening_time;
    
    
-- price list

SELECT
    type_name technology,
    TO_CHAR(price, '9,999.99') base_price
FROM
    screening_types;

-- discount list

SELECT
    id,
    description,
    TO_CHAR(percent_off * 100)
    || ' %' percent_off
FROM
    discounts;
